### ISSUE TITLE
Информация о людях

### ISSUE THREAD

**Issue by dimqua** [odin3/Avi#43]
Хотелось бы, чтобы приложение отображало больше информации с кинопоиска, в частности, информацию о людях: актерах, режиссерах и т.д.

**Comment by catbaxter** [comment]
Imho, большого смысла нет, все это и даже больше есть в приложении Кинопоиск. Вот интеграцию с Кинопоиском (подставлять приложение по действию "Открыть на Кинопоиске") очень бы имело смысл.

**Comment by x1unix** [comment]
@dimqua, на данный момент согласен с @catbaxter. Возможно в далеком будущем это будет реализовано, но на данный момент думаю будет просто переход на страницу актера, режиссера.
